version: '3.8'
services:
  openbb:
    environment:
      DISPLAY: host.docker.internal:0.0
    volumes:
      - ~/OpenBBUserData:/home/python/OpenBBUserData
      - ~/.openbb_terminal:/home/python/.openbb_terminal
    platform: linux/amd64
    image: ghcr.io/openbb-finance/openbbterminal/openbb:latest
    stdin_open: true # docker run -i
    tty: true # docker run -t
